# Nombre de tu sitio web (se ver치 en el encabezado)
name: Nombre de tu sitio

# Descripci칩n de tu sitio web (se ver치 en el encabezado)
description: Otro sitio hecho en Jekyll

# Url de tu imagen de perfil
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Excluir archivos del sitio ya generado en producci칩n
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
